### ISSUE TITLE
Hang after SendRaw

### ISSUE THREAD

**Issue by madbot69** [qwertzguy/Spark-Core-IRremote#1]
Hi there,

Used this code for my SparkCore to send Raw Code in place of the Arduino unit. The Mitsubishi air cond successfully receives the (very long) raw code. Thanks for the great work..!

However, after sending the raw code the SparkCore seems to hang for 5 minutes or more. Do you know if this is because the raw code is too long? The Arduino did not take this long to respond. In my code below, the last println line is printed after 5 minutes or more:
# 

  Serial1.println("Sending Power On!");

  unsigned int AirCondOn[] = {3400,1700,400,1200,400,1200,400,400,400,400,450,400,400,1200,450,400,400,400,450,1200,450,1200,450,400,400,1200,450,400,400,400,400,1200,400,1200,400,400,450,1200,450,1200,450,400,450,400,400,1200,400,400,400,400,400,1200,450,400,400,400,400,400,450,400,400,400,450,400,450,400,450,400,400,400,450,400,450,400,400,400,400,400,400,400,400,400,400,400,400,400,450,1200,450,400,450,400,450,1200,450,400,450,400,400,1200,400,1200,400,400,400,400,450,400,400,400,400,400,450,400,450,1200,450,1200,400,400,400,1200,400,400,400,400,400,400,400,400,400,400,400,1200,450,400,450,400,450,400,450,400,450,400,400,400,450,400,400,400,400,400,400,400,400,400,400,400,400,400,450,400,450,400,400,400,450,400,450,400,450,400,400,400,450,400,400,400,400,400,450,400,400,400,400,400,400,400,400,400,450,400,400,400,450,400,450,400,400,400,400,400,450,400,450,400,400,400,450,400,400,1200,400,400,400,400,450,1200,400,400,450,400,400,1200,450,400,450};  
  irsend.sendRaw(AirCondOn, 230, 38);
  Serial1.println("Code Sent!");
# 

Many thanks,

Update:
The "hang" was due to the mismatch of number of commands (230) specified in the sendRaw vs the actual number of commands specified in the array (227). After changing 230 to 227 everything worked fine. Thanks

**Comment by qwertzguy** [comment]
Hey @madbot69,

For some reason I never got a notification for this issue.
Glad that you found the problem!

I'll close the issue.

Gaspard
