### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by tkodev** [qwertzguy/Spark-Core-IRremote#2]
I'm aware the project hasn't been updated in two years, however, I've been trying to compile your library along with a very simple sketch in "particle dev" ide, 

```
// Library
  #include "IRremote.h"
  IRsend irsend(A5);
// Setup
  void setup() {
  }
// Loop
  void loop() {
  }
```

results in a strange compile error: 

```
build didn't produce binary Error: Command failed: ../../../build/target/user/platform-6-m/4d5c9cbc6fbb22e9b2ef4aba8a74a5fb674888c75789e84783007064a667//libuser.a(IRremote.o): In function `__static_initialization_and_destruction_0':
/spark/compile_service/shared/workspace/6_platform_6_24_2/firmware/4d5c9cbc6fbb22e9b2ef4aba8a74a5fb674888c75789e84783007064a667/
IRremote.cpp:3: undefined reference to `IRsend::IRsend(int)'
collect2: error: ld returned 1 exit status
make: *** [/spark/compile_service/shared/workspace/6_platform_6_24_2/firmware/4d5c9cbc6fbb22e9b2ef4aba8a74a5fb674888c75789e84783007064a667/4d5c9cbc6fbb22e9b2ef4aba8a74a5fb674888c75789e84783007064a667.elf] Error 1
```

I haven't edited the .h and .cpp files at all and they are sitting in the directory of the .ino file, as this is the way to do it in Particle Dev (not the online build!)

Oddly enough, it works completely fine in online Particle Build.

I'm too much of a novice to know if this is a library error or a compiler/ide error, can anyone comfirm?

**Comment by qwertzguy** [comment]
Hey,

I never used Particle Studio but it seems like it doesn't find the .h file as an include file. Check the configuration of the project or compiler to make sure that the include paths have the directory where you put the .h file.

**Comment by tkodev** [comment]
Solution at https://community.particle.io/t/irremote-library-compile-error/21810/4  ! 

Basically, my sketch was named the same name as the library, simple error on my part! sorry & thanks for replying!

**Comment by qwertzguy** [comment]
Cool, good to know!
